version: "3.9"
services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
    volumes:
      - .:/app
    command: ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]