FROM python:3.9-slim

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . /techtrack

WORKDIR /techtrack

EXPOSE 23000

CMD ["python", "test_preprocessing.py"]